on:
  push: # Trigger the workflow when code is pushed
    branches:
      - master # Only trigger on pushes to the 'main' branch

jobs: 
  build:
    runs-on: ubuntu-latest # Use Ubuntu for the runner environment
    steps:
      - name: Compile SCSS
        uses: gha-utilities/sass-build@v0.4.7
        with:
          source: /styles/scss/styles.scss
          destination: /styles/scss/styles.css